# Generated by Django 5.1.6 on 2025-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Pid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
